[config]
cc = "clang"
ld = "clang"
as = "clang"

[project]
sub = [["bake", "bake"]]
# TODO: Support git builds?
ext = [["tomlc99", "libtoml"]]

[project.bake]
srcs = "."
bin = "."
ccflags = ["-std=c23", "-g"]
incflags = ["-I.", "-Itomlc99/"]
ldflags = ["-Ltomlc99", "-ltoml"]
type = "exec"
binname = "bake"
deps = []

[ext.libtoml]
loc = "tomlc99"
chdir = "."
buildcmd = ["make"]
